---
commandLineParameters:
- LogLine:
    value: 2
- LogOption:
    value: 4
- ErrMsg:
    value: 0
- ErrorLog:
    value: 99
- ResLim:
    value: 30
- Threads:
    value: 12
- OptCR:
    value: 1e-6
- OptCA:
    value: .001
- ErrNam:
    value: error
- SolverStat:
    value: gams_solverstat.log
- LogFile:
    value: gams_logfile.log
- Output:
    value: gams_output.log
environmentVariables:
- GRB_LICENSE_FILE:
    value: C:\gurobi910\gurobi.lic
...
